version: "2"
services:
  mysql:
    image: mysql/mysql-server:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: ileague
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql:/data
    ports:
      - "3306:3306"
