spring:
  application:
    name: ileague
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/ileague
    username: app
    password: app
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        # do not convert column names to snake-case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl